version: "3"
services:
  redis:
    image: redis:3.2-alpine
    privileged: true
    ports:
      - 6379:6379
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      main:
        aliases:
          - redis

  postgresqldb:
    container_name: postgresqldb
    image: healthcheck/postgres:alpine
    privileged: true
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: easypeng1l0o
      POSTGRES_DB: postgres
    volumes:
      - /usr/local/var/postgres:/var/lib/postgresql/data/
    networks:
      main:
        aliases:
          - postgresqldb
networks:
  main:
    driver: bridge
