logging:
  level:
    com.netflix.eureka: off
    com.netflix.discovery: off
server:
  port: 8761
eureka:
  instance:
    prefer-ip-address: false
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  # 注册中心的自我保护，当注册应用下线时立即下线，开发环境使用，生产环境不使用
  server:
    enable-self-preservation: false
---
spring:
  profiles: docker
server:
  port: 8761
eureka:
  instance:
    prefer-ip-address: false
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/